name: Build Docker Image for ECR

on:
  workflow_call:
    inputs:
      ecr_repo:
        type: string
        required: true
      aws_region:
        type: string
        required: false
        default: 'us-east-2'
    outputs:
      image:
        value: ${{ jobs.build_image.outputs.image }}

jobs:
  build_image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    outputs:
      image: ${{ steps.push.outputs.image }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<YOUR-GH-ACTIONS-ROLE>
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image URI
        id: meta
        run: |
          IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repo }}:${{ github.sha }}"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"

      - name: Build and push image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: true
          tags: ${{ steps.meta.outputs.image }}

